[package]
name = "marketing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "2.1.3"
cw-storage-plus = "2.0.0"
serde = "1.0.205"
sylvia = "1.1.0"
